#!/usr/bin/env node
'use strict'

const fs = require('fs')

var code = `var express = require('express')
var bodyParser = require('body-parser')
var router = express.Router()

// create application/json parser
var jsonParser = bodyParser.json()

/**
   * @param {{e.RequestHandler}} jsonParser
   * @param {{changes:Array<Array<int>>, source:String}} req.body
   */
  router.post('/aftercreatecol', jsonParser, function (req, res, next) {

  // TODO: If you want to use this method implement your code here
  res.json({'status': 'OK'})
})

/**
 * @param {{e.RequestHandler}} jsonParser
 * @param {{changes:[{row:number,column:number,newValue:string}}], source:String}} req.body
   */
router.post('/afterchange', jsonParser, function (req, res, next) {

  // TODO: If you want to use this method implement your code here
  res.json({'status': 'OK'})
})

/**
   * @param {{e.RequestHandler}} jsonParser
   * @param {{changes:Array<Array<int>>, source:String}} req.body
   */
  router.post('/aftercreaterow', jsonParser, function (req, res, next) {

  // TODO: If you want to use this method implement your code here
  res.json({'status': 'OK'})
})

/**
 * @param {{e.RequestHandler}} jsonParser
 * @param {{changes:Array<Array<int>>, source:String}} req.body
 */
router.post('/aftercolumnsort', jsonParser, function (req, res, next) {

  // TODO  insert implementation here
  res.json({'data': 'ok'})
})
/**
 * @param {{e.RequestHandler}} jsonParser
 * @param {{changes:Array<Array<int>>, source:String}} req.body
 */
router.post('/aftercolumnmove', jsonParser, function (req, res, next) {

  // TODO  insert implementation here
  res.json({'data': 'ok'})
})

module.exports = router
`

var generate = (name) => {
  if (name !== '') {
    fs.writeFile('../routes/' + name + '.js', code, (err) => {
      if (err) {
        console.log('Can not create file')
        program.exit(-1)
      } else {
        console.log('File has been created in routes folder')
      }
    })
  }
}

const program = require('commander')
program
  .version('0.0.1')
  .description('Generate express js hot controller')
  .action(generate)

program
  .parse(process.argv)

